"""
Export service — convert AI-generated text into downloadable files.

Supported formats: pdf, docx, xlsx, pptx, txt
"""
import io
import re
from datetime import datetime


def _clean(text: str) -> str:
    """Strip markdown bold/italic markers for non-markdown renderers."""
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'\*(.+?)\*', r'\1', text)
    text = re.sub(r'`(.+?)`', r'\1', text)
    return text


# ── PDF ───────────────────────────────────────────────────────────────────────

def to_pdf(content: str, title: str = "BankAi Export") -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.enums import TA_LEFT, TA_CENTER

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=2.5*cm, leftMargin=2.5*cm,
        topMargin=2.5*cm, bottomMargin=2.5*cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("BankTitle", parent=styles["Title"],
                                 fontSize=16, spaceAfter=6, textColor=colors.HexColor("#1e3a5f"))
    meta_style  = ParagraphStyle("Meta", parent=styles["Normal"],
                                 fontSize=9, textColor=colors.grey, spaceAfter=12)
    h1_style    = ParagraphStyle("H1", parent=styles["Heading1"],
                                 fontSize=13, textColor=colors.HexColor("#1e3a5f"), spaceBefore=14, spaceAfter=4)
    h2_style    = ParagraphStyle("H2", parent=styles["Heading2"],
                                 fontSize=11, textColor=colors.HexColor("#2d6a9f"), spaceBefore=10, spaceAfter=3)
    body_style  = ParagraphStyle("Body", parent=styles["Normal"],
                                 fontSize=10, leading=15, spaceAfter=6)
    bullet_style = ParagraphStyle("Bullet", parent=styles["Normal"],
                                  fontSize=10, leading=14, leftIndent=18, spaceAfter=3,
                                  bulletText="•")

    story = []
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(f"Generated by BankAi — {datetime.now().strftime('%d %b %Y, %H:%M')}", meta_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1e3a5f"), spaceAfter=12))

    for line in content.splitlines():
        t = line.strip()
        if not t:
            story.append(Spacer(1, 6))
        elif t.startswith("### "):
            story.append(Paragraph(_clean(t[4:]), h2_style))
        elif t.startswith("## ") or t.startswith("# "):
            story.append(Paragraph(_clean(t.lstrip("#").strip()), h1_style))
        elif t.startswith(("• ", "- ", "* ")):
            story.append(Paragraph(_clean(t[2:]), bullet_style))
        elif re.match(r"^\d+\.\s", t):
            story.append(Paragraph(_clean(t), bullet_style))
        elif t == "---":
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey, spaceAfter=8))
        else:
            story.append(Paragraph(_clean(t), body_style))

    doc.build(story)
    return buf.getvalue()


# ── DOCX ──────────────────────────────────────────────────────────────────────

def to_docx(content: str, title: str = "BankAi Export") -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin    = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin   = Inches(1.2)
        section.right_margin  = Inches(1.2)

    # Title
    t = doc.add_heading(title, 0)
    t.runs[0].font.color.rgb = RGBColor(0x1e, 0x3a, 0x5f)

    # Metadata
    meta = doc.add_paragraph(f"Generated by BankAi — {datetime.now().strftime('%d %b %Y, %H:%M')}")
    meta.runs[0].font.size = Pt(9)
    meta.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)
    doc.add_paragraph()

    for line in content.splitlines():
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph()
        elif stripped.startswith("### "):
            doc.add_heading(_clean(stripped[4:]), level=3)
        elif stripped.startswith("## "):
            doc.add_heading(_clean(stripped[3:]), level=2)
        elif stripped.startswith("# "):
            doc.add_heading(_clean(stripped[2:]), level=1)
        elif stripped.startswith(("• ", "- ", "* ")):
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(_clean(stripped[2:]))
        elif re.match(r"^\d+\.\s", stripped):
            p = doc.add_paragraph(style="List Number")
            p.add_run(_clean(re.sub(r"^\d+\.\s", "", stripped)))
        else:
            doc.add_paragraph(_clean(stripped))

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ── XLSX ──────────────────────────────────────────────────────────────────────

def to_xlsx(content: str, title: str = "BankAi Export") -> bytes:
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = title[:31]  # Excel sheet name limit

    header_font  = Font(bold=True, color="FFFFFF", size=11)
    header_fill  = PatternFill("solid", fgColor="1e3a5f")
    title_font   = Font(bold=True, size=14, color="1e3a5f")
    thin_border  = Border(bottom=Side(style="thin", color="CCCCCC"))

    ws["A1"] = title
    ws["A1"].font = title_font
    ws["A2"] = f"Generated by BankAi — {datetime.now().strftime('%d %b %Y, %H:%M')}"
    ws["A2"].font = Font(italic=True, size=9, color="888888")
    ws.append([])

    # Try to detect if content looks tabular (has | or \t separators)
    lines = [l for l in content.splitlines() if l.strip()]
    is_table = any("|" in l or "\t" in l for l in lines[:5])

    if is_table:
        # Render as a proper table
        row_num = 4
        first_data_row = True
        for line in lines:
            if "|" in line:
                cells = [c.strip() for c in line.strip().strip("|").split("|")]
                if all(set(c) <= set("- :|") for c in cells):
                    continue  # markdown separator row
                ws.append(cells)
                if first_data_row:
                    for cell in ws[ws.max_row]:
                        cell.font = header_font
                        cell.fill = header_fill
                        cell.alignment = Alignment(horizontal="center")
                    first_data_row = False
            elif "\t" in line:
                ws.append(line.split("\t"))
            else:
                ws.append([line])
            row_num += 1
    else:
        # Render as labelled rows: heading → bold, bullets → indented
        for line in lines:
            stripped = line.strip()
            if not stripped:
                ws.append([])
            elif stripped.startswith(("# ", "## ", "### ")):
                text = _clean(stripped.lstrip("#").strip())
                ws.append([text])
                ws.cell(row=ws.max_row, column=1).font = Font(bold=True, size=11, color="1e3a5f")
            elif stripped.startswith(("• ", "- ", "* ")):
                ws.append(["", _clean(stripped[2:])])
            else:
                ws.append([_clean(stripped)])

    # Auto-width
    for col in ws.columns:
        max_len = max((len(str(cell.value or "")) for cell in col), default=10)
        ws.column_dimensions[col[0].column_letter].width = min(max_len + 4, 80)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


# ── PPTX ──────────────────────────────────────────────────────────────────────

def to_pptx(content: str, title: str = "BankAi Export") -> bytes:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor

    prs = Presentation()
    BANK_BLUE = RGBColor(0x1e, 0x3a, 0x5f)
    BANK_MID  = RGBColor(0x2d, 0x6a, 0x9f)

    def _title_slide(prs, title_text, subtitle_text=""):
        layout = prs.slide_layouts[0]
        slide  = prs.slides.add_slide(layout)
        slide.shapes.title.text = title_text
        slide.shapes.title.text_frame.paragraphs[0].runs[0].font.color.rgb = BANK_BLUE
        if slide.placeholders[1]:
            slide.placeholders[1].text = subtitle_text
        return slide

    def _content_slide(prs, slide_title, bullets):
        layout = prs.slide_layouts[1]
        slide  = prs.slides.add_slide(layout)
        slide.shapes.title.text = slide_title
        slide.shapes.title.text_frame.paragraphs[0].runs[0].font.color.rgb = BANK_BLUE
        tf = slide.placeholders[1].text_frame
        tf.clear()
        first = True
        for b in bullets:
            if first:
                p = tf.paragraphs[0]
                first = False
            else:
                p = tf.add_paragraph()
            p.text = b
            p.level = 0
        return slide

    _title_slide(prs, title, f"Generated by BankAi — {datetime.now().strftime('%d %b %Y')}")

    # Split content into slides at each H1/H2 heading
    current_heading = "Overview"
    current_bullets: list[str] = []

    for line in content.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith(("# ", "## ", "### ")):
            if current_bullets:
                _content_slide(prs, current_heading, current_bullets)
                current_bullets = []
            current_heading = _clean(stripped.lstrip("#").strip())
        elif stripped.startswith(("• ", "- ", "* ")):
            current_bullets.append(_clean(stripped[2:]))
        elif re.match(r"^\d+\.\s", stripped):
            current_bullets.append(_clean(stripped))
        else:
            current_bullets.append(_clean(stripped))
        # Split slide if too many bullets
        if len(current_bullets) >= 7:
            _content_slide(prs, current_heading, current_bullets)
            current_bullets = []

    if current_bullets:
        _content_slide(prs, current_heading, current_bullets)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


# ── TXT ───────────────────────────────────────────────────────────────────────

def to_txt(content: str, title: str = "BankAi Export") -> bytes:
    header = (
        f"{title}\n"
        f"{'=' * len(title)}\n"
        f"Generated by BankAi — {datetime.now().strftime('%d %b %Y, %H:%M')}\n\n"
    )
    return (header + content).encode("utf-8")


# ── Dispatcher ────────────────────────────────────────────────────────────────

MIME_TYPES = {
    "pdf":  "application/pdf",
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "txt":  "text/plain; charset=utf-8",
}

EXTENSIONS = {"pdf": ".pdf", "docx": ".docx", "xlsx": ".xlsx", "pptx": ".pptx", "txt": ".txt"}

GENERATORS = {
    "pdf":  to_pdf,
    "docx": to_docx,
    "xlsx": to_xlsx,
    "pptx": to_pptx,
    "txt":  to_txt,
}


def export(content: str, fmt: str, title: str = "BankAi Export") -> tuple[bytes, str, str]:
    """Returns (file_bytes, mime_type, filename)."""
    fmt = fmt.lower().lstrip(".")
    if fmt not in GENERATORS:
        raise ValueError(f"Unsupported format: {fmt}. Choose from: {', '.join(GENERATORS)}")
    data = GENERATORS[fmt](content, title)
    safe_title = re.sub(r"[^\w\s-]", "", title).strip().replace(" ", "_")[:50] or "export"
    filename = f"{safe_title}{EXTENSIONS[fmt]}"
    return data, MIME_TYPES[fmt], filename
